### ISSUE TITLE
which version of Detectron2 for detection to use?

### ISSUE THREAD

**Issue by sasa123123** [KaiyuYue/mgd#6]
hi, thank you for your job.
Could you please provide software version which you used for this job, such as torch, torchvision, detectron2, python, ...

Thanks!

**Comment by kaiyuyue** [comment]
For sure, here they are

- Python - 3.7
- PyTorch - 1.5.0 with torchvision - 0.6.0
- Detectron2 -  Tree - [369a57d333](https://github.com/facebookresearch/detectron2/tree/369a57d333ff9c05c9dd42ab3c3d8156860dc710)

I have added these to README. Thanks very much.

**Comment by KaiyuYue** [comment]
For sure, here they are

- Python - 3.7
- PyTorch - 1.5.0 with torchvision - 0.6.0
- Detectron2 -  Tree - [369a57d333](https://github.com/facebookresearch/detectron2/tree/369a57d333ff9c05c9dd42ab3c3d8156860dc710)

I have added these to README. Thanks very much.
